name: Deploy site to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Compute baseURL (custom domain aware)
        id: baseurl
        shell: bash
        env:
          CUSTOM_DOMAIN: ${{ vars.CUSTOM_DOMAIN }}
        run: |
          set -euo pipefail
          # 1) Prefer repository variable CUSTOM_DOMAIN if set
          if [[ -n "${CUSTOM_DOMAIN:-}" ]]; then
            DOMAIN="$CUSTOM_DOMAIN"
            URL="https://${DOMAIN}/"
          # 2) Else prefer static/CNAME in repo if present
          elif [[ -f static/CNAME ]]; then
            DOMAIN="$(tr -d '\r\n' < static/CNAME)"
            URL="https://${DOMAIN}/"
          # 3) Else fall back to GitHub Pages project/user URL
          else
            OWNER="${GITHUB_REPOSITORY%/*}"
            REPO="${GITHUB_REPOSITORY#*/}"
            if [[ "$REPO" == *.github.io ]]; then
              URL="https://${REPO}/"
            else
              URL="https://${OWNER}.github.io/${REPO}/"
            fi
          fi
          echo "url=${URL}" >> "$GITHUB_OUTPUT"
          echo "domain=${DOMAIN:-}" >> "$GITHUB_OUTPUT"

      - name: Build
        env:
          HUGO_ENV: production
        run: |
          hugo --gc --minify --baseURL "${{ steps.baseurl.outputs.url }}"

      - name: Ensure CNAME in artifact when using custom domain
        if: ${{ steps.baseurl.outputs.domain != '' }}
        run: |
          echo "${{ steps.baseurl.outputs.domain }}" > public/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
